// Code generated by forgexml UI generator. DO NOT EDIT.
// Source: /home/mmcnew/repos/forgexml-scap/schemas/arf/asset-reporting-format_1.1.0.xsd
// Schema: Asset Reporting Format 1.1

package main

import (
	"embed"
	"flag"
	"fmt"
	"log"
	"os"

	_ "github.com/aequo-labs/forgexml-scap/internal/generated/gov/nist/scap/schema/asset-reporting-format/1-1"
	"github.com/aequo-labs/webserver-core-ui/pkg/webserver"

	"github.com/aequo-labs/forgexml-scap/cmd/ui/internal/handlers"
	"github.com/aequo-labs/forgexml-scap/cmd/ui/internal/state"
)

//go:embed static
var staticFiles embed.FS

//go:embed templates
var templateFiles embed.FS

//go:embed schemas
var schemaFiles embed.FS

//go:embed docs
var docsFiles embed.FS

var (
	version   = "dev"
	buildTime = "unknown"
	gitCommit = "unknown"
)

func main() {
	// Command line flags
	port := flag.Int("port", 8080, "Port to listen on")
	inputFile := flag.String("input", "", "XML file to load on startup")
	showVersion := flag.Bool("version", false, "Show version information")
	flag.Parse()

	if *showVersion {
		fmt.Printf("Asset Reporting Format 1.1 UI Editor\n")
		fmt.Printf("Version: %s\n", version)
		fmt.Printf("Build Time: %s\n", buildTime)
		fmt.Printf("Git Commit: %s\n", gitCommit)
		os.Exit(0)
	}

	// Create UI server
	srv, err := webserver.NewUIServer(nil)
	if err != nil {
		log.Fatalf("Failed to create UI server: %v", err)
	}

	// Add application templates from subdirectories
	templateDirs := []string{"templates/pages", "templates/forms", "templates/includes"}
	for _, dir := range templateDirs {
		if err := srv.AddTemplatesFromFS(templateFiles, dir); err != nil {
			// Directory might not exist, that's okay
			log.Printf("Note: Could not load templates from %s: %v", dir, err)
		}
	}

	// Add application static assets
	srv.AddAssetsFromFS(staticFiles, "static", "/app-static/")

	// Initialize XML document state
	docState := state.NewXMLDocumentState()

	// Load input file if provided
	if *inputFile != "" {
		if err := docState.LoadFromFile(*inputFile); err != nil {
			log.Fatalf("Failed to load input file %s: %v", *inputFile, err)
		}
		log.Printf("Loaded XML document from %s", *inputFile)
	}

	// Create handlers with state
	h := handlers.NewHandlers(srv, docState, schemaFiles)

	// Register routes
	router := srv.Router()

	// Page routes
	router.HandleFunc("GET /", h.HandleHome)
	router.HandleFunc("GET /tree", h.HandleTreeView)
	router.HandleFunc("GET /edit", h.HandleEditElement)
	router.HandleFunc("GET /create", h.HandleCreateElement)
	router.HandleFunc("GET /export", h.HandleExportPage)

	// Tree API endpoints
	router.HandleFunc("GET /api/tree/root", h.HandleTreeRoot)
	router.HandleFunc("GET /api/tree/children", h.HandleTreeChildren)
	router.HandleFunc("GET /api/tree/element", h.HandleTreeElement)

	// CRUD API endpoints
	router.HandleFunc("GET /api/elements/{type}", h.HandleListElements)
	router.HandleFunc("GET /api/element", h.HandleGetElement)
	router.HandleFunc("POST /api/element", h.HandleCreateElementAPI)
	router.HandleFunc("PUT /api/element", h.HandleUpdateElement)
	router.HandleFunc("DELETE /api/element", h.HandleDeleteElement)

	// Import/Export API endpoints
	router.HandleFunc("POST /api/import", h.HandleImport)
	router.HandleFunc("GET /api/export", h.HandleExport)
	router.HandleFunc("GET /api/export/preview", h.HandleExportPreview)
	router.HandleFunc("POST /api/validate", h.HandleValidate)

	// Health check endpoint for status indicator
	router.HandleFunc("GET /api/health", h.HandleHealth)

	// Type information API endpoints
	router.HandleFunc("GET /api/types", h.HandleListTypes)
	router.HandleFunc("GET /api/types/root", h.HandleGetRootTypes)
	router.HandleFunc("GET /api/types/{name}", h.HandleGetType)
	router.HandleFunc("GET /api/types/{name}/concrete", h.HandleGetConcreteTypes)
	router.HandleFunc("GET /api/types/{name}/children", h.HandleGetValidChildTypes)

	// Set about information
	srv.SetAboutInfo(webserver.AboutInfo{
		AppName:     "Asset Reporting Format 1.1 Editor",
		Version:     version,
		Description: "XML Editor for Asset Reporting Format 1.1 documents",
		Features: []string{
			"Visual tree navigation of XML structure",
			"CRUD operations on all element types",
			"XSD validation",
			"Import/Export XML files",
			"Abstract type handling with dropdowns",
			"Enum support with select inputs",
		},
		Links: []webserver.NavItem{
			{Title: "ForgeXML", URL: "https://github.com/aequo-labs/forgexml"},
		},
		ExtraInfo: map[string]string{
			"Schema":    "Asset Reporting Format 1.1",
			"Namespace": "http://scap.nist.gov/schema/asset-reporting-format/1.1",
			"Source":    "/home/mmcnew/repos/forgexml-scap/schemas/arf/asset-reporting-format_1.1.0.xsd",
		},
	})

	// Register documentation filesystem (XSD schema docs)
	srv.RegisterDocsFS(docsFiles, "docs")

	// Set navigation items
	srv.SetPageDataEnricher(func(data *webserver.PageData) {
		data.NavItems = []webserver.NavItem{
			{Title: "Home", URL: "/"},
			{Title: "Tree View", URL: "/tree"},
			{Title: "Export", URL: "/export"},
		}
		data.AppName = "Asset Reporting Format 1.1 Editor"
		data.Version = version
		data.ShowAbout = true
	})

	// Start server
	addr := fmt.Sprintf(":%d", *port)
	log.Printf("Starting Asset Reporting Format 1.1 Editor on port %d", *port)
	log.Printf("Open http://localhost:%d in your browser", *port)
	if err := srv.ListenAndServe(addr); err != nil {
		log.Fatalf("Server error: %v", err)
	}
}
